# Generated by Django 3.1.1 on 2020-11-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201006_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reviews', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
